title: ITA UNSSC
description: Website to follow the UNSSC digital accessibility evaluation. You'll find all the documents listing users and technical issues.

permalink: pretty
remote_theme: "https://github.com/just-the-docs/just-the-docs"
heading_anchors: true
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-optional-front-matter
  - jekyll-default-layout